name: wear
description: A plugin that offers Flutter support for Wear OS by Google
version: 2.0.0
homepage: https://github.com/fluttercommunity/flutter_wear_plugin

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mjohnsullivan.flutterwear.wear
        pluginClass: WearPlugin
